name: 'Update CNAME'

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize]
     
jobs:
  terraform:
    name: 'Update CNAME'
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
        unzip terraform_0.15.5_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
    - name: Initialize Terraform
      run: terraform init
    - name: Terraform Format
      run: terraform fmt -check
    - name: Plan Terraform
      run: terraform plan
#    - name: Apply Terraform
#      if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
#      run: terraform apply -auto-approve -input=false
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
